### PR TITLE
Benchmarks: Docker + Memory bench

### PR DESCRIPTION
**Pull request by cameron-git**
Current Issues:

- [x] Memory graphs MB formatting
- [x] EXODUS not working
- [x] ModuleNotFoundError: No module named 'sinabs'
- [x] ModuleNotFoundError: No module named 'spikingjelly' (Was working previously)
- [x] copy fig folder from container not working
- [x] Remove non-torch libs from mem graphs
- [x] Add batch_size to graph titles
- [ ] lava-dl 4.0.0 supports torch 1.13.1 while 4.0.0dev supports 2.0.0. Hopefully 5.0.0 soon.
- [x] Norse not working with torch2.0.0
- [x] JAX thinks Cuda11.7 is installed
- [x] Splits forward, backward and total
- [x] Build Lava from source
- [x] Add figs to post
- [x] Clone repo in container instead of COPY at build

### CODE REVIEW

**Comment by biphasic** [comment]
The latest version of Lava-DL needs Pytorch > 2.0 
https://github.com/lava-nc/lava-dl/blob/main/pyproject.toml#L62
it's not released yet but maybe pip installing it from source could be easier than trying to re-install torch 1.13

Regarding Sinabs, pip install sinabs should work out of the box and doesn't contain any compiled code
Regarding Exodus, that one should be able to compile as long as CUDA is correctly installed https://github.com/synsense/sinabs-exodus#prerequisites

**Comment by cameron-git** [comment]
# Library sticking points
## Lava-DL

Install from source or get a new release on GH that supports torch2 and cuda12

## Spyx

Because of the following spyx is currently running on cupy

Possible solutions:
- Lava-DL update and use torch2.1.0 with cuda12
- Install jax in container

```
CUDA backend failed to initialize: Found CUDA version 11070, but JAX was built against version 11080, which is newer. The copy of CUDA that is installed must be at least as new as the version against which JAX was built. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
```
```
# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

## Norse

**Comment by cameron-git** [comment]
# Comments on Mem usage

snnTorch seems very efficient if results are accurate.

**Comment by cameron-git** [comment]
# Stylistic Update

- [ ] Bigger text
- [ ]

**Comment by cameron-git** [comment]
# Stylistic Update

- [ ] Bigger text
- [ ]

**Comment by cameron-git** [comment]
Just putting an update here. Norse does not work with pytorch 2.0.0 and installing lava-dl from source forces pytorch 2.0.0 while its mypy package uses an older version.
Im not sure where this leaves this PR but in my mind id rather support norse so thats what ive done with torch 2.1.0.
I run the build.sh and then bench.sh, then manually install and run lava after in a new container and update the datafile manually.

There is a new datafile and images. The images can be tweaked using the plot.py file. The run used batch size of 16

**Comment by biphasic** [comment]
this is really nice! Installing Lava is such a pain...
Two remarks: 
1. I think we should change the post into using only the 16k neuron plots now, 1 latency and 1 memory
2. Could you please change the unit for the memory plot to GB and round to 2 digits after the comma
Let's integrate it into the post and then we're good to go I think

**Comment by cameron-git** [comment]
I've added the figs to the post and updated some sections to reflect the new results and memory benchmark.
I tested with hugo and the figure load fine.
I also added myself as 4th author, is that okay?

**Comment by biphasic** [comment]
That's really cool, thanks a lot for that! I pushed a few small updates to the text and the figures. I'm going to merge it now! 

One more question, you commented out
> Benchmarks are averaged across 100 runs on a NVIDIA A100 GPU with 40GB of vRAM.  Standard deviations have been omitted because they are negligible.

is the repetition not the case anymore?

**Comment by cameron-git** [comment]
> is the repetition not the case anymore?
I thougtht it wasnt but the time it function runs the passes multiple times, however the number of times is non-deterministic. minimum of 3 runs and minimum of 2s total runtime.
I have a prototype im working on, when i bench that, I can run again with a higher min runs

**Pull request merged**
