### PR TITLE
Updated SNN benchmark blog content

### PR DESCRIPTION
**Pull request by Jegp**
I realized the blog text was outdated. I took a stab at revitalizing it, including a brief introduction to `torch.compile` and the possible reasons why it helps to much with runtime + memory overhead.

Happy to hear feedback and suggestions for improvements

### CODE REVIEW

**Comment by Jegp** [comment]
I also discovered that the Lava benchmark failed. Somehow the most recent lava-dl package crashes (no such package).

**Comment by biphasic** [comment]
Installing Lava is a pain. Could you please try following their original instructions? https://github.com/lava-nc/lava-dl?tab=readme-ov-file#installation

**Comment by Jegp** [comment]
Ok. Yeah, that was indeed a pain. Lava insists on using a local venv (via Poetry), so I had to rearrange the docker to install everything inside the lava venv. But now it works, and Lava is added.

**Comment by biphasic** [comment]
thanks so much man! merging this now.

**Pull request merged**
