### PR TITLE
Add social media icons to the website footer

### PR DESCRIPTION
**Pull request by Rhig**
image

The icons will appear in the bottom of the website no matter which page you're on.

### CODE REVIEW

**Comment by Rhig** [comment]
This is for https://github.com/open-neuromorphic/open-neuromorphic.github.io/issues/6 - is there a way to show it is related?

**Comment by fabrizio-ottati** [comment]
Actually we would need the icons to fit with the website style. A possible idea it to lose the contour leaving only the logos. and fill these using the same colors of the website. The color in HEX is 719CFE.

**Comment by Rhig** [comment]
I did my best but I can't really choose the color of the Discord logo (I think FontAwesome provide it only if you pay money).
Here's how it looks now:

image

**Comment by fabrizio-ottati** [comment]
I think it is really nice like this! I would say perfect! Is it possible to lower them just a little bit, so that their bottoms align with the bottom of the footer?

**Comment by Rhig** [comment]
I hope this is aligned, I don't have a good eye for these kinds of things:
image

**Comment by fabrizio-ottati** [comment]
Actually, I see that on mobile it gets messed up. Could put the logos *above* the footer? In the meanwhile I merged.

**Comment by fabrizio-ottati** [comment]
Feel free to create another PR for that

**Pull request merged**
