### PR TITLE
Redesign proposal

### PR DESCRIPTION
**Pull request by neural-loop**
**Objective:** The goal of this redesign is to enhance the website's user experience, improve searchability, and provide a more prominent platform for workshops and contributors.

Key Changes:

- **Workshop Focus**: We propose branding events as "workshops" and giving them a more prominent role on the website. This change emphasizes the educational aspect and encourages participation.
- **Content Organization**: To improve searchability, we recommend creating dedicated pages for blogs and workshops. This separation allows users to easily find relevant content.
- **SEO Optimization**: Titles have been reworked to clarify technologies, making the website more discoverable through organic search.
- **Contributor Showcase**: Effort has been put into showcasing contributors' contributions, particularly in workshop efforts, to acknowledge their valuable contributions to the community.
- **Taxonomies (tags/categories)**: Disabled these as there isn't enough unique content. Consider there are maybe ~25 pages and 15 tags, each tag creates a unique feed page. It creates a scenario where more than half the site content (according to search) is mostly redundant. If the content grows to many hundreds of pages, tags could make more sense as they would not make a large proportion of the indexed site content
- **Discord emphasis**: There is a prominent call out to Discord which appears at the top right of each page. A slight 'glow' around it draws attention to the area as a contrast in style to the clean lines elsewhere. At the same time it's not distracting or intrusive.  
-  **External links**: An icon is added to links via css that indicates if a link will open to a new tab

Additional Enhancements:

-   Credits: A credit section has been added at the bottom of the page to acknowledge contributors and partners.
-   Dev Log: A brief "dev log" near the bottom of the About page provides insight into ongoing developments and improvements. This could be extended to include prior efforts, and also encourage contributions. 

Feedback and Revisions: I welcome your thoughts and questions. Feel free to provide feedback or request revisions to align the redesign with your specific needs.

- On the workshops page, I was experimenting with two different layout styles (a wide horizontal, and a column style) I kind of feel that the horizontal has a better feel to it, and maybe should extend throughout.

For testing, run it with: 
```hugo serve --buildFuture```

### CODE REVIEW

**Comment by biphasic** [comment]
Thanks for the great work. Which version of Hugo are you using? When I run ```hugo serve --buildFuture``` I get
```
Module "hugoplate.netlify.app" is not compatible with this Hugo version
```
I'm using v0.111.3

Also, do you see a possibility to embed the Discord widget?

**Comment by neural-loop** [comment]
The Hugo version I have is hugo v0.119.0-b84644c008e0dc2c4b67bd69cccf87a41a03937e+extended linux/amd64 BuildDate=2023-09-24T15:20:17Z VendorInfo=snap:0.119.0

The minimums I see are

- [Hugo Extended v0.115+](https://gohugo.io/installation/)
- [Node v18+](https://nodejs.org/en/download/)
- [Go v1.20+](https://go.dev/doc/install)

I did update a few different areas to highlight Discord, I think anyone visiting will notice. 

Looking into the widget, it wasn't quite what I thought it was and I didn't see a good place for it. It's a simple themed list of users / online status with a small join button at the bottom and I didn't see that itself it was more compelling than the other call outs. 

I could experiment a bit more with it, it seems better would be to maybe have some sort of custom widget that displays specific details ( ### users online! ), rather than a iframe list of usernames.

**Comment by biphasic** [comment]
I managed to get it running on my system. If anyone else has an issue with an outdated Hugo version, I installed it as Snap package.

I like the website design! A few things I noticed:
1. For the `Spiking Nerual Network (SNN) Library Benchmarks` blog post, the header is cut off when I open the post.
2. Can we make the light theme default?
3. Discord button is great
4. In the light theme, the little subwindow that opens for the About header, it is completely black
5. For the banners for the workshops, is this a coded / automated approach, or did you create those manually? I would prefer some kind of automated approach

**Comment by neural-loop** [comment]
Glad you got it running! 

**For the `Spiking Neural Network (SNN) Library Benchmarks` blog post, the header is cut off when I open the post.**

The post header image serves a dual purpose, both as a visual on the website and as the share image for social media posts. To optimize this, we can create or crop images to a standard size of 1280x720 pixels, which will ensure a consistent display on the website while also enhancing the shareability of content on platforms like LinkedIn and Twitter. This way, users won't miss out on important information due to cropping.

Currently, the images are cropped for the benefit of less visual clutter and disorganization, we would need to update the existing source images to 1280x720 to have the full benefits:




**Can we make the light theme default?**

Certainly, I'll make the light theme the default option. My preference is for the dark theme but it's easy to toggle.

**In the light theme, the little subwindow that opens for the About header is completely black.**

I'll get that fixed!

**For the banners for the workshops, is this a coded / automated approach, or did you create those manually? I would prefer some kind of automated approach.**

In points 1 and 5, the use of these are relating to the image modifications to serve multiple purposes (social media sharing, YouTube thumbnails, and website) This approach helps us provide broader coverage in various domains without the need to create multiple assets for each purpose.

We have the option to switch the workshop header images to use auto-generated thumbnails, but I strongly advise maintaining consistent thumbnails. It's important to consider that many viewers will encounter these thumbnails when deciding whether to engage with the content through YouTube recommendations. This initial impression is a valuable opportunity to capture their attention.

A random screenshot from the middle of a Zoom session may not effectively convey the essence of the workshop or entice viewers. Creating clear and engaging thumbnails provides a compelling value proposition, maximizing the impact of the speakers' and editors' time and commitment







Feel free to let me know if you have any more questions or if there's anything else you'd like to address!

**Comment by neural-loop** [comment]
For dark / light mode, there is an option "system" which would try to determine if the user has a dark mode enabled. I think that it would fall back to light mode. I'll try pushing with that for a quick round of testing.

**Comment by biphasic** [comment]
> . It's important to consider that many viewers will encounter these thumbnails when deciding whether to engage with the content through YouTube recommendations. This initial impression is a valuable opportunity to capture their attention.

This is a very good point which I agree with. My main concern is the following: if we schedule new talks, how hard is it to generate the thumbnail? Is there a template one can use?

**Comment by neural-loop** [comment]
[thumbnail-template.zip](https://github.com/open-neuromorphic/open-neuromorphic.github.io/files/12795242/thumbnail-template.zip)

This is the template I used for creating the thumbnails (using photopea, which has a huge selection of fonts.) I got the background image from a site that hosts public domain images, I'm trying to remember what I searched for to track down its provenance. 

If you really want to automate it, we can try to make something. I don't think that hugo has font support for creating images, but I've done this in python before to generate transparent text layers automatically: [example](https://youtu.be/qoZQjnGtbe8?si=7MCcubk_iX0XTBRA&t=469) I still manually created the thumbnails for the reasons mentioned before. 

The issue is some months down the road, when you want to change the thumbnail style, introduce new colors or adjust things it would take redesigning some aspects of the code. Also, attention would have to be paid to the title lengths. Typically if you just have a few words, you can make them larger - and a longer title would use smaller text to fit it within a region. Possibly you could set up a formula characters / fontsize.. but maybe can see where this could get over engineered compared to a template.

**Comment by neural-loop** [comment]
On the header being cut off, it was the image you referred to or something else? I was looking at the current images and noticed they also exhibited cropping, at a different aspect ratio. 

[Spiking neurons: a digital hardware implementation](https://open-neuromorphic.org/p/spiking-neurons-a-digital-hardware-implementation/) Here the top and bottom are cropped. I think that in the scenario of ```Spiking Nerual Network (SNN) Library Benchmarks``` the source image was closer to the crop dimension, which is why the top of the image is seen.

**Comment by neural-loop** [comment]
Here is the source of the background image in the thumbnails https://unsplash.com/photos/XgeZu2jBaVI

**Comment by neural-loop** [comment]
I'm looking into adding a table of contents section that updates as you scroll to the blog posts, as they are rather long and deserve a bit more attention. Will probably create a right column of the content section and put the table of contents & social sharing with it. 

Looking into it. 

Do you have any more questions or thoughts?

**Comment by biphasic** [comment]
it looks very good already. Thanks for the thumbnail template. A few more things I noticed:
1. Upcoming Workshop doesn't show anything
2. Large vertical space above Recent Workshops and Recent Posts
3. When using the light theme, there is a white box in the bottom right corner on the page

**Comment by neural-loop** [comment]
1. Upcoming Workshop doesn't show anything 
Could you verify it's being built with "--buildFuture"? One thing I could think of is without buildFuture it might not be picking up the dates of the workshops that have a future date set. Is it on the landing page, or landing page & workshops page?
2. Large vertical space above Recent Workshops and Recent Posts
The contents were in different sections. The vertical space would make sense if there were more diverse sections throughout the page, with alternating background colors & styles (I mention this in that you may see the vertical space again if you add a new section in the future, and I would suggest experimenting with some background color styles). Since they are both rows of cards it does seem like a large gap. I updated it to put both rows into the same section.
3. I've added a couple screenshots for review. Something seems a bit off about the column alignment without it, though the spacer probably isn't the best way to resolve that.

No spacer:
image

Spacer no background gradient:
image

**Comment by neural-loop** [comment]
The updated blog entries (table of contents) I couldn't get the scrollspy dialed in that highlights the ToC to show where you're at, though I think this makes the blog posts more digestible overall) 

image

**Comment by neural-loop** [comment]
I did a bit of research on auto generating the images, sharing here. I thought the image feature didn't have text but I see it does.
https://www.himpler.com/en/blog/auto-generate-og-images-for-hugo/
Could be something useful for blog posts

**Comment by biphasic** [comment]
this is really nicely coming together. Instead of 'sharing is caring', can we just write 'share this site' please?

**Comment by neural-loop** [comment]
Updated  sharing is caring to share this site, and changed checks to discs

**Comment by neural-loop** [comment]
I don't see anything at the moment! I'll keep an eye out for any updates requested after launch and folks have a chance to look around more.

**Pull request merged**
