### PR TITLE
Benchmarks

### PR DESCRIPTION
**Pull request by aMarcireau**
@biphasic @fabrizio-ottati 

My commit messages are not particularly useful and I had a hard time creating partial commits with the notebook. Here's a brief summary of the changes to the benchmarks code:

- added UNDR formats (numpy and Brotli). Note: compressing with Brotli -11 is crazy slow and took 50 minutes to complete.
- added event_stream (a streaming ES decoder) to compare with Loris's non-streaming approach.
- added a hash function to ensure that all algorithms return the same events.
- removed standard library modules from requirements.txt, and added missing dependencies.
- added a log-axis version of the figure (to better compare fast formats).
- ran the benchmarks with Python 3.10 on a 2017 15" MacBook Pro (2.9 GHz i7, 16 GB 2133 MHz LPDDR3, APFS SSD).
- removed the .es file download (the file is now derived from the .aedat file).
- added explicit garbage collection to minimise memory usage during benchmarks (probably not particularly impactful).
- saved the results as JSON.
- replaced MB with MiB.

A few observations

- EVT2 / EVT3 are really good. We should discuss whether to use them for UNDR (the UNDR spec supports any number of encodings).
- EVT2 prints a WARNING (the timestamps are not monotonic). It outputs the same events as the other libraries and the events are monotonic (I added a check in the notebook). This might be a bug in Expelliarmus.
- UNDR currently uses unaligned numpy arrays. They outperform aligned arrays in time and file size (but may not meet other constraints imposed by the GPU or C/C++ code).

### CODE REVIEW

**Comment by biphasic** [comment]
This is amazing stuff, thank you so much! We can also convert it to a normal Python script at this point if that makes things easier. It's interesting that for example the h5py benchmarks look different on your machine. I do agree that evt2/3 look very promising, this is thanks to @fabrizio-ottati who optimized the reading.

**Comment by fabrizio-ottati** [comment]
Thank you @aMarcireau! I will look into the EVT2 bug :) 
Yes, the EVT2 encoding is pretty good, while I don't think that EVT3 is worth it 'cause I don't know how many times you are able to vectorize. 

With Brotli I made a mess, thanks for suggesting a much more efficient way of dealing with it! BTW I tried to compress the DAT format with `brotli -q 0` and I obtain a better compression than EVT2. Do you think that we can use brotli C API to support decoding in the C source code?

**Comment by aMarcireau** [comment]
Since the Brotli C source is reasonably self-contained (https://github.com/google/brotli/tree/master/c), it should not be too hard to add it to Expelliarmus (or any other Python extension). This will probably result in a trade-off between decoding speed and size.

Longer term, I think we should take inspiration from Brotli, EVT, and video compression formats (and perhaps Event Stream) to build new custom formats (lossy and / or lossless) that outperform everything else. This is actually the idea that pushed me the put UNDR together.

**Comment by fabrizio-ottati** [comment]
https://github.com/deepmind/compressed_vision

**Pull request merged**
